# Generated by Django 5.0.6 on 2024-06-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedextension',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedextension',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usedextension',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
