# Generated by Django 5.0.6 on 2024-06-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensionapp', '0002_usedextension_floor_usedextension_hostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedextension',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
